Add categorical generators
sdv-dev/RDT pull request #201
Opened 2021-07-24 02:09 UTC by sarahmish

1. add categorical generators and tests for LabelEncoder and Categorical transformers.
2. small tweak for LabelEncoder to allow input of type `np.ndarray`

2021-07-26 16:53 UTC, csala requested changes

2021-07-26 16:53 UTC, csala commented on tests/performance/datasets/categorical.py
> +    TYPE = 'numerical'
Would this (and the type for the others) not be `categorical` instead?

2021-07-26 16:53 UTC, csala commented on tests/performance/datasets/categorical.py
> +"""Dataset Generators for categorical transformers."""
Should we add a dataset that produces a mixture of types?
We should also think about adding other types that can be used as categories, like `datetimes`, `floats` or `bools`.
Maybe it is not necessary to add explicitly datasets for each possible type, but at least have one dataset that produces a mixture of all of them, as well as NaNs and Nones.

2021-07-27 13:56 UTC, csala approved these changes
I think this looks great @sarahmish !
Any thoughts @amontanez24 ?

2021-07-27 20:25 UTC, amontanez24 approved these changes
I think this is good to merge!

2021-07-28 14:06 UTC, merged