Add flake8-use-fstring  addon to enforce the f-string usage.
sdv-dev/RDT pull request #272
Opened 2021-10-02 00:16 UTC by pvk-developer

As part of #248  added `flake8-use-fstring` to enforce the usage of `f'{variable}'` and changed the code where the old `.format` was being used.

2021-10-04 18:59 UTC, katxiao commented
Could we achieve the same thing by removing `SFS1` and  `SFS2` from `extend-ignore` [here](https://github.com/sdv-dev/RDT/blob/master/setup.cfg#L37)?

2021-10-04 18:59 UTC, katxiao reviewed
Could we achieve the same thing by removing `SFS1` and  `SFS2` from `extend-ignore` [here](https://github.com/sdv-dev/RDT/blob/master/setup.cfg#L37)?

2021-10-05 02:47 UTC, amontanez24 approved these changes
I like this a lot! :shipit:

2021-10-05 14:02 UTC, csala approved these changes
Approved. We can review the version range, though

2021-10-05 14:02 UTC, csala commented on setup.py
> +    'flake8-use-fstring>=1.1,<1.2',
I think we can push this to <2

2021-10-05 14:09 UTC, csala requested changes
Actually taking the approval back.

I agree with @katxiao : The result of this PR is an overlap of two plugins: `flake8-sfs` and `flake8-use-fstring`, which cover the same functionality.

I think that the PR needs to be updated to either:
- Remove the `flake8-sfs` plugin and its ignores from the `setup.cfg`
- Remove the `flake8-use-fstring` plugin and remove the `SFS2` ignore from `setup.cfg`, so only f-strings are accepted. Unless there is a problem with `flake8-sfs` that I am not aware of, I would go for this one, since we are already using this one without issues

2021-10-06 11:57 UTC, merged