Update NullTransformer to make it user friendly
sdv-dev/RDT pull request #384
Opened 2022-02-07 12:56 UTC by pvk-developer

### NullTransformer
With the current `PR` the `NullTransformer` contains the following changes:
* Always works with a copy of the data (no changes occur to the original data).
* Adapt unit tests and integration tests.
* New user friendly names for the fill value / nan and null column:
    * `fill_value` or `nan` becomes -> `missing_value_replacement`.
    * `null_column` becomes -> `model_missing_values`.

#### `missing_value_replacement`
By default this value will be `None` which will not replace the values. From python perspective this will return `np.nan` which should be the representation of `Null`.

The second strategy is the user specifying a string `mode` or `mean` , which will use the `mode` of the data or the `mean` value (if possible) as a replacement of the `null` values that are in the data.

The third strategy is the user specifying a value for it which will be used to fill the null values with.

#### `model_missing_values`
By default this value will be `False`. If set to `True` it will generate a new column representing if there was a missing value or not. In the case that the data had no missing values this column will not be generated.

Resolves #372 , #362 , #376

2022-02-07 19:25 UTC, amontanez24 requested changes
Looking good. I left a few comments

2022-02-07 19:25 UTC, amontanez24 commented on rdt/transformers/null.py
> +    def fit(self, data, column):
If the only reason we are passing this is for the warning message then I'm not sure we need it. Couldn't we get the column name by doing `data.name`?

2022-02-07 19:25 UTC, amontanez24 commented on rdt/transformers/null.py
> +    def creates_model_missing_values(self):
minor: I'd call this `models_missing_values`

2022-02-07 19:25 UTC, amontanez24 commented on rdt/transformers/boolean.py
>              Defaults to ``-1``.
This isn't true anymore right?

2022-02-09 01:07 UTC, pvk-developer commented on rdt/performance/performance.py
> +        'missing_value_replacement': -1,
I used the `default` that was before on the `BooleanTransformer` . I think that it's okay to leave it is, however in the following changes to the baseclass we can change this to be the same 
````python
null_transformer_args = { 
    missing_value_replacement: 'mean'
    model_missing_value: True,
}
if transformer.supports_null(): # or something like that ?
    transformer_instance = transformer(**null_transformer_args)
````

2022-02-09 14:12 UTC, fealho commented on tests/unit/transformers/test_null.py
> +        If there are no nulls in the data and model_missing_values was given as None,
as False, not none.

2022-02-09 14:21 UTC, fealho commented on tests/unit/transformers/test_numerical.py
> +        ct.null_transformer = NullTransformer(None, model_missing_values=None)
not None

2022-02-09 15:58 UTC, pvk-developer commented on rdt/transformers/null.py
> +            return np.nan
Nice catch, I made a lot of changes, this should return `None` and when we do `fillna` we check if this is not `None`  to actually proceed with the replacement 👍🏻

2022-02-09 16:17 UTC, pvk-developer commented on rdt/transformers/datetime.py
> +            Indicate what to do with the null values. If an object is given, replace them
Yes in my mind it made sense to put `str, int, float or None` but then of course `False` or `True` could be an option so I decided to use `object` as a generic word to whatever is being passed will be used to replace the `nan` values.

2022-02-09 16:47 UTC, pvk-developer commented on rdt/transformers/null.py
> +                'Extra column not created.'
I mention it on the docstring but let me think of a better message.

2022-02-09 18:15 UTC, pvk-developer commented on tests/unit/transformers/test_numerical.py
> +          missing_value_replacement.
😅 make sure to use case sensitive when replacing 🤦🏻‍♂️

2022-02-09 18:27 UTC, amontanez24 approved these changes
One minor comment but once you finish addressing that and the other comments it should be good to go!

2022-02-09 18:27 UTC, amontanez24 commented on rdt/transformers/boolean.py
> +            with the given value. If the strings ``'mean'`` or ``'mode'`` are given, replace
I guess we should remove `mean` since that doesn't really make sense for booleans

2022-02-09 19:17 UTC, fealho commented on tests/unit/transformers/test_numerical.py
> +          missing_value_replacement.
After you put the `NaN`'s back I think it's good to go.

2022-02-09 19:29 UTC, fealho approved these changes
A few more NaN's to change back.

2022-02-09 19:29 UTC, fealho commented on tests/unit/transformers/test_numerical.py
> -        - First column of the input array rounded, replacing the indicated value with a Nan,
here.

2022-02-09 19:29 UTC, fealho commented on tests/unit/transformers/test_numerical.py
> -        """Test the _learn_rounding_digits method with data that is all NaNs.
here

2022-02-09 19:29 UTC, fealho commented on tests/unit/transformers/test_numerical.py
> -        If the data is all NaNs, expect that the output is None.
here

2022-02-09 19:29 UTC, fealho commented on tests/unit/transformers/test_numerical.py
> -        - An array of NaNs.
here

2022-02-10 01:25 UTC, merged