Validate the `transform` method
sdv-dev/RDT pull request #481
Opened 2022-04-07 16:37 UTC by fealho

Resolve #479.

2022-04-08 19:17 UTC, amontanez24 requested changes
One small text change, but once that's done it should be ready to go!

2022-04-08 19:17 UTC, amontanez24 commented on rdt/hyper_transformer.py
> -                "Use the method 'get_config()' to see the expected values."
This line should still be included according to the issue

2022-04-11 17:43 UTC, amontanez24 approved these changes
LGTM!

2022-04-12 11:08 UTC, pvk-developer approved these changes
:shipit:

2022-04-12 13:26 UTC, merged