Add add-on detection for transformers
sdv-dev/RDT pull request #647
Opened 2023-05-17 15:46 UTC by frances-h

2023-05-22 18:46 UTC, pvk-developer requested changes

2023-05-22 18:46 UTC, pvk-developer commented on rdt/__init__.py
> +            global scope. Defaults to ``False``.
Not needed anymore right?

2023-05-22 18:46 UTC, pvk-developer commented on rdt/__init__.py
> +        base_module = modules[__name__]
Could `modules` be `sys.modules` ? Took me a while to understand where this variable magically appears from.

2023-05-22 18:46 UTC, pvk-developer commented on rdt/__init__.py
> +                continue
I would suggest to move all this to a `process_entry_point` function. And maybe try to even split that into multiple steps if possible.

2023-05-23 09:46 UTC, fealho commented on tests/unit/test___init__.py
> +    modules_mock['rdt'].submodule.entry_name == 'entry_point'
assert

2023-05-23 09:46 UTC, fealho commented on tests/unit/test___init__.py
> +    modules_mock['rdt'].submodule.entry_name.entry_object.entry_method == 'new_method'
assert

2023-05-24 20:49 UTC, pvk-developer approved these changes
LGTM! Thanks for addressing the comments!

2023-05-25 10:25 UTC, fealho approved these changes
After you fix lint, :shipit:

2023-05-25 14:40 UTC, merged