Add test for `LabelEncoder` with `add_noise=True` for 'category' pandas dtype
sdv-dev/RDT pull request #856
Opened 2024-07-31 17:35 UTC by fealho

CU-860q1dv6r, Resolve #617.

2024-07-31 17:35 UTC, sdv-team commented
Task linked: [CU-860q1dv6r RDT - LabelEncoder() with add_noise = True does not Support 'category' pandas dtype #617](https://app.clickup.com/t/860q1dv6r)

2024-07-31 17:54 UTC, amontanez24 reviewed
Just to sanity check can we reverse transform in the test as well?

2024-08-01 15:41 UTC, gsheni requested changes

2024-08-01 15:41 UTC, gsheni commented on tests/integration/transformers/test_categorical.py
> +    data_test = data_test.astype('category')
```suggestion
    data_test = pd.DataFrame({'A': pd.Series(['a', 'b', 'a', 'a', 'c'], dtype='category' )})
```

2024-08-01 15:41 UTC, gsheni commented on tests/integration/transformers/test_categorical.py
> +    data_test = data_test.astype('category')
Also, lint is failing

2024-08-05 17:37 UTC, amontanez24 approved these changes

2024-08-06 15:26 UTC, gsheni approved these changes

2024-08-06 16:52 UTC, merged